name: autodeploy

on:
  push:

jobs:
  deploy:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: install dependencies
        run: npm i

      - name: run deploy script
        run: npm run deploy
